normalizacion = { # MLS
              "Atlanta United FC": "Atlanta United",
              "New York City FC": "New York City FC",
              "Nashville Soccer Club": "Nashville SC",
              "FC Cincinnati": "FC Cincinnati",
              "New York Red Bulls": "NY Red Bulls",
              "Orlando City SC": "Orlando City SC",
              "Philadelphia Union": "Philadelphia Union",
              "Houston Dynamo": "Houston Dynamo",
              "Saint Louis City SC": "Saint Louis City SC",
              "Real Salt Lake": "Real Salt Lake",
              "Austin FC": "Austin FC",
              "Colorado Rapids": "Colorado Rapids",
              "Vancouver Whitecaps": "Vancouver Whitecaps",
              "Sporting Kansas City": "Sporting Kansas City",
              "Los Angeles FC": "Los Angeles FC",
              "Seattle Sounders": "Seattle Sounders",
              "Columbus SC": "Columbus Crew",
              "DC United": "DC United",
              "Inter Miami CF": "Inter Miami CF",
              "San Jose": "San Jose Earthquakes",
              "Minnesota United": "Minnesota United FC",
              "": "New England Revolution", 
              "Montreal Impact": "CF Montréal",
              "Charlotte": "Charlotte FC",
              "Orlando City": "Orlando City SC",
              "FC Toronto": "Toronto FC",
              "FC Dallas": "Dallas",
              "Los Angeles Galaxy": "LA Galaxy",
              "Portland Timbers": "Portland Timbers",
              "Chicago Fire": "Chicago Fire",
              # Internacionales
              "China": "China",
              "Birmania": "Myanmar",
              "China Taipei": "China Taipéi",
              "Tailandia": "Thailand",
              "Corea del Sur": "Corea del Sur", 
              "Perú": "Perú",
              "Nueva Zelanda": "Nueva Zelanda",
              "Suecia": "Suecia",
              "Serbia": "Serbia",
              "Jordania": "Jordania",
              "Polonia": "Polonia",
              "Alemania": "Alemania",
              "Colombia": "Colombia",
              "Irak": "Irak",
              "Chile": "Chile",
              "República Dominicana": "República Dominicana",
              "Brasil": "Brasil",
              "Guinea": "Guinea",
              "Ecuador": "Ecuador",
              "Bolivia": "Bolivia",
              "Paraguay": "Paraguay",
              "Nicaragua": "Nicaragua",
              # Libertadores
              "Athlético Paranaense": "Athlético Paranaense",
              "Alianza Lima": "Alianza Lima",
              "Club Libertad Asunción": "Libertad",
              "Atlético Mineiro": "Atlético-MG",
              "Atlético Nacional": "Atlético Nacional",
              "Patronato": "Patronato",
              "Fluminense FC": "Fluminense",
              "Sporting Cristal": "Sporting Cristal",
              "Club Olimpia": "Olimpia",
              "FBC Melgar": "FBC Melgar",
              "River Plate": "River Plate",
              "The Strongest": "The Strongest",
              "SC Internacional": "Internacional",
              "Independiente Medellin": "Independiente Medellin",
              "Club Nacional": "Nacional de Montevideo",
              "Metropolitanos FC": "Metropolitanos",
              "Corinthians": "Corinthians", 
              "Liverpool Montevideo": "Liverpool",
              "Flamengo": "Flamengo",
              "Aucas": "Aucas",
              "Independiente del Valle": "Independiente del Valle",
              "Argentinos Juniors": "Argentinos Juniors",
              "Racing Club": "Racing Club",
              "Ñublense": "Nublense",
              "Boca Juniors": "Boca Juniors",
              "Monagas SC": "Monagas",
              "Colo-Colo": "Colo Colo",
              "Deportivo Pereira": "Deportivo Pereira",
              "Barcelona SC": "Barcelona Guayaquil",
              "Cerro Porteño": "Cerro Porteno",
              "Palmeiras": "Palmeiras",
              "Club Bolívar": "Bolívar",
              # Copa Sudamericana
              "Palestino": "Palestino",
              "Fortaleza EC": "Fortaleza",
              "San Lorenzo": "San Lorenzo",
              "Estudiantes de Merida": "Estudiantes de Merida",
              "São Paulo": "São Paulo",
              "Tigre": "Tigre",
              "Deportes Tolima": "Deportes Tolima",
              "Academia Puerto Cabello": "Academia Puerto Cabello",
              "Red Bull Bragantino": "Bragantino",
              "Tacuary Asuncion": "Tacuary",
              "Estudiantes de La Plata": "Estudiantes LP",
              "Oriente Petrolero": "Oriente Petrolero",
              "Clube Guaraní": "Guarani",
              "CA Huracan": "Huracan",
              "Emelec": "Emelec",
              "Danubio": "Danubio",
              "Santa Fe": "Independiente Santa Fe",
              "Goiás EC": "Goiás",
              "Universitario de Deportes": "Universitario de Deportes",
              "Gimnasia y Esgrima La Plata": "Gimnasia",
              "Newell's Old Boys": "Newell's",
              "Audax Italiano": "A. Italiano",
              "Botafogo FR": "Botafogo-RJ",
              "Magallanes": "Deportes Magallanes",
              "CA Peñarol": "Peñarol",
              "América-MG": "América-MG",
              "Defensa y Justicia": "Defensa y Justicia",
              "Millonarios": "Millonarios",
              "LDU Quito": "LDU Quito",
              "Cesar Vallejo": "Universidad Cesar Vallejo",
              "Blooming Santa Cruz": "Blooming",
              # Brasil Serie A
              "São Paulo": "Sao Paulo",
              "Fortaleza EC": "Fortaleza",
              "Esporte Clube Bahia": "Bahia",
              "Grêmio FBPA": "Gremio",
              "Grêmio": "Gremio",
              "SC Internacional": "Internacional",
              "Red Bull Bragantino": "Bragantino",
              "Botafogo FR": "Botafogo",
              "Botafogo-RJ": "Botafogo",
              "Cuiabá EC": "Cuiaba",
              "Cuiabá": "Cuiaba",
              "Santos FC": "Santos",
              "Goiás EC": "Goias",
              "Goiás": "Goias",
              # Argentina Primera División
              "Lanús": "Lanus",
              "Arsenal de Sarandi": "Arsenal Sarandi",
              "Vélez Sársfield": "Velez Sarsfield",
              "Atlético Tucumán": "Atletico Tucuman",
              "Unión de Santa Fe": "Union de Santa Fe",
              "Central Córdoba": "Central Cordoba",
              "Talleres de Córdoba": "Talleres",
              "Colón de Santa Fe": "Colon",
              "CA Belgrano": "Belgrano",
              "Instituto AC Cordoba": "Instituto de Córdoba",
              "CA Sarmiento": "Sarmiento",
              # Brasil Serie B
              "Guarani SP": "Guarani",
              "Mirassol FC": "Mirassol",
              "Atlética Ponte Preta": "Ponte Preta",
              "Ituano FC": "Ituano",
              "Atlético Goianiense": "Atlético",
              "Vila Nova FC": "Vila Nova",
              "ABC Futebol": "ABC",
              "Avaí FC": "Avai SC",
              "Criciúma EC": "Criciúma",
              "Sampaio Corrêa FC": "Sampaio Correa",
              "EC Vitória": "Vitoria",
              "EC Juventude": "Juventude",
              # Australia NSW
              "Sydney FC Youth": "Sydney FC S21",
              "Sydney United 58": "Sydney United",
              "APIA Leichhardt Tigers": "Leichhardt Tigers",
              "Bull FC Academy": "Northbridge FC",
              "Blacktown City FC": "Blacktown City",
              "Marconi Stallion": "Marconi Stallions",
              "Western Sydney Wanderers Juveniles": "Western Sydney Wanderers",
              "Western Sydney Wanderers FC Youth": "Western Sydney Wanderers",
              "NWS Spirit FC": "NWS Spirit",
              "NSW Spirit": "NWS Spirit",
              "Central Coast Mariners Juveniles": "C. Coast Mariners",
              "Mt Druitt Town Rangers FC": "Mt. Druid Town Rangers",
              # Australia West
              "Armadale SC": "Armadale",
              "Balcatta FC": "Balcatta",
              "Inglewood Utd": "Inglewood United",
              "Ecu Joondalup": "ECU Joondalup",
              "Sorrento FC": "Sorrento",
              # Amistosos de Clubes
              "Maccabi Haifa FC": "Maccabi Haifa",
              "Universitatea Cluj": "U. Cluj",
              "FK Viktoria Žižkov": "Viktoria Zizkov",
              "MŠK Považská Bystrica": "MSK Povazska Bystrica",
              "FC Slovan Liberec": "Slovan Liberec",
              "FK Varnsdorf": "Varnsdorf",
              "FC Copenhagen": "Copenhague",
              "LKS Lódz": "LKS Lodz",
              "Cracovia Kraków": "Cracovia",
              "FC Baník Ostrava": "Banik Ostrava",
              "FK Austria Wien": "FK Austria Viena",
              "Floridsdorfer AC": "FAC Wien",
              "MFK Karviná": "MFK Karvina",
              "FK Železiarne Podbrezová": "Zeleziarne Podbrezova",
              "Diósgyöri VTK": "DVTK",
              "SSV Jahn Regensburg": "Regensburg",
              "Fortuna Köln": "SC Fortuna Cologne",
              "Rapid Bucuresti": "Rapid",
              "TSV Prolactal Hartberg": "Hartberg",
              "1. FC Nürnberg": "Nurnberg",
              "RWD Molenbeek 47": "RWD Molenbeek",
              "KV Kortrijk": "Kortrijk",
              "Patro Eisden Maasmechelen": "Patro Maasmechelen",
              "St. Truidense VV": "Sint-Truidense VV",
              "FC Dundee": "Dundee",
              # Liga MX
              "FC Juárez": "Juarez",
              "Mazatlán FC": "Mazatlán",
              "Club Tijuana": "Xolos de Tijuana",
              "Atlético San Luis": "Atletico San Luis",
              "Querétaro": "Queretaro",
              # Uruguay Primera División
              "Montevideo Wanderers": "Wanderers",
              "Montevideo City Torque": "Torque",
              "CA Boston River": "Boston River",
              "Centro Atlético Fénix": "Fenix",
              "Racing Club de Montevideo": "Racing Club",
              "CA Cerro": "Cerro",
              "Cerro Largo FC": "Cerro Largo",
              "Deportivo Maldonado": "Maldonado",
              "La Luz FC": "La Luz",
              # Suecia Allsvenskan
              "IFK Värnamo": "IFK Varnamo",
              "Malmö FF": "Malmo FF",
              "IFK Göteborg": "IFK Goteborg",
              "BK Häcken": "BK Hacken",
              "IFK Norrköping": "IFK Norrkoping FK",
              "Djurgårdens IF": "Djurgardens IF",
              "Varbergs BoIS": "Varbergs BOIS",
              "Mjällby AIF": "Mjallby AIF",
              # Perú Primera División
              "Universidad Técnica de Cajamarca": "UTC Cajamarca",
              "Asociacion Deportiva Tarma": "Tarma",
              "EM Deportivo Binacional": "Binacional",
              "Unión Comercio": "Union Comercio",
              "Atlético Grau": "Atletico Grau",
              # Noruega Eliteserien
              "Vålerenga": "Valerenga",
              "Viking FK": "Viking",
              "Aalesunds FK": "Aalesunds",
              "Rosenborg BK": "Rosenborg",
              "Hamarkameratene": "Ham-Kam",
              "Odds Ballklubb": "Odds",
              "Lillestrom SK": "Lillestrom",
              "Tromsø": "Tromsoe",
              "Sandefjord Fotball": "Sandefjord",
              "Bodø/Glimt": "Bodo Glimt",
              "Strømsgodset": "Stromsgodset",
              "Stabæk": "Stabaek",
              # Noruega Primera División
              "Hødd": "Hodd",
              "Kristiansund BK": "Kristiansund",
              "Mjøndalen": "Mjondalen",
              "Åsane": "Asane",
              "Sandnes Ulf": "Sandnes",
              "Kongsvinger IL": "Kongsvinger",
              # Japón Liga J
              "Kyoto Sanga FC": "Kyoto Sanga",
              "Albirex Niigata Albi": "Niigata Albirex",
              "Yokohama F Marinos": "Yokohama Marinos",
              # Irlanda Premier League
              "Drogheda United FC": "Drogheda United",
              "Dundalk FC": "Dundalk",
              "Shamrock Rovers FC": "Shamrock Rovers",
              "Saint Patrick´s Athletic FC": "St. Patrick's Athletic",
              "University College Dublín": "UCD",
              "Derry City FC": "Derry City",
              "Bohemians Dublín": "Bohemians",
              "Sligo Rovers FC": "Sligo Rovers",
              # Irlanda First Division
              "Athlone Town AFC": "Athlone Town",
              "Cobh Ramblers FC": "Cobh Ramblers",
              "Bray Wanderers AFC": "Bray Wanderers",
              "Finn Harps FC": "Finn Harps",
              "Waterford FC": "Waterford United",
              "Longford Town FC": "Longford Town",
              "Wexford FC": "Wexford",
              # Finlandia Veikkausliga
              "FC Haka Valkeakoski": "FC Haka",
              "Seinajoen JK": "SJK",
              "Vaasan Palloseura": "VPS",
              "FC KTP Kotka": "KTP",
              # Egipto Premier League
              "Aswan SC": "Aswan",
              "ENPPI": "Enppi",
              "Pharco FC": "Farco",
              "Al-Mokawloon al-Arab": "Al Mokawloon",
              "El Geish": "El Gaish",
              # China Super Liga
              "Shanghai Port FC": "Shanghai Port",
              "Shandong Taishan FC": "Shandong Luneng Taishan",
              "Chengdu Better City": "Chengdu Rongcheng",
              "Tianjin TEDA FC": "Tianjin Teda",
              "Meizhou Hakka FC": "Meizhou Hakka",
              "Nantong Zhiyun F.C": "Nantong Zhiyun FC",
              "Shijiazhuang Ever Bright": "Cangzhou Mighty Lions",
              "Zhejiang Greentown FC": "Zhejiang Greentown",
              # Amistosos de Clubes
              "Bohemians Prague 1905": "Bohemians 1905",
              "Zalaegerszegi TE": "Zalaegerszeg",
              "FC Lugano": "Lugano",
              "FC Farul Constanta": "Constanta",
              "F.Constanta": "Constanta",
              "MK Pogon Szczecin": "Pogon Szczecin",
              "FC Koper": "Koper",
              "Crvena Zvezda": "Red Star"
              } 

ligas = {'playdoit': [
  'https://www.playdoit.mx/#period=all&sportids=66&categoryids=0&champids=4610&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#period=all&sportids=66&categoryids=0&champids=3645&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#period=all&sportids=66&categoryids=0&champids=3709&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#period=all&sportids=66&categoryids=0&champids=3108&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#period=all&sportids=66&categoryids=0&champids=11318&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#period=all&sportids=66&categoryids=0&champids=3075&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#sportids=66&categoryids=0&champids=11005&period=all&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#sportids=66&categoryids=0&champids=4969&period=all&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#sportids=66&categoryids=0&champids=4807&period=all&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#sportids=66&categoryids=0&champids=2932&period=all&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#period=all&sportids=66&categoryids=0&champids=10009&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#sportids=66&categoryids=0&champids=4632&period=all&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#sportids=66&categoryids=0&champids=3537&period=all&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#sportids=66&categoryids=0&champids=4042&period=all&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#sportids=66&categoryids=0&champids=3458&period=all&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#sportids=66&categoryids=0&champids=3541&period=all&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#sportids=66&categoryids=0&champids=3951&period=all&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#sportids=66&categoryids=0&champids=3571&period=all&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#sportids=66&categoryids=0&champids=4208&period=all&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#sportids=66&categoryids=0&champids=4593&period=all&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#sportids=66&categoryids=0&champids=2974&period=all&marketGroupId=0&catids=0&page=prelive',
  'https://www.playdoit.mx/#sportids=66&categoryids=0&champids=8622&period=all&marketGroupId=0&catids=0&page=prelive'
], 'codere': [
    'https://apuestas.codere.mx/es_MX/t/45638/MLS?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/19287/Amistosos-Internacionales?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/47052/Copa-Libertadores?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/48428/Copa-Sudamericana?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/45823/Serie-A-Brasil?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/46735/Liga-Profesional?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/45487/Serie-B-Brasil?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/45642/Australia-National-Premier-League-NSW?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/45746/Australia-National-Premier-League-Western?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/45807/Amistosos-de-Clubes?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/45349/Liga-MX?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/45529/Primera-Divisi%C3%B3n-Uruguay?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/45425/Allsvenskan?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/45621/Primera-Divisi%C3%B3n-Per%C3%BA?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/49140/Eliteserien?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/45624/Divisi%C3%B3n-1-Noruega?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/45643/J-League?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/45633/Premier-League-Irlanda?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/45735/Irlanda-First-Division?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/45427/Veikkausliiga?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/45399/Premier-League-Egipto?mkt_sort=HCTG',
    'https://apuestas.codere.mx/es_MX/t/45376/China-Super-League?mkt_sort=HCTG'
]}

nombres = ['MLS', 'Amistosos Internacionales', 'Libertadores', 'Copa Sudamericana', 'Brasil Serie A', 'Argentina Primera División', 
           'Brasil Serie B', 'Australia NSW', 'Australia West', 'Amistosos de Clubes', 'Liga MX', 'Uruguay Primera Divisón', 
           'Suecia Allsvenskan', 'Perú Primera División', 'Noruega Eliteserien', 'Noruega Primera División', 'Japón Liga J',
           'Irlanda Premier League', 'Irlanda First Division', ' Finlandia Veikkausliga', 'Egipto Premier League', 'China Super Ligan']